Feature/#16 상품 상세 api 완료
FC-InnerCircle/icd01-team05_06-commerce-be pull request #17
Opened 2024-09-16 16:58 UTC by hun-cloud

상품 상세 api 개발 완료했습니다.
저번에 같이 보았던
restdocs pathvariable이 숫자로 표현되는 이슈가 있는데 어떻게 수정했는지 소스 비교해봐도 찾기가 힘드네요..

2024-09-17 13:02 UTC, psh10066 approved these changes
잘 작성해주신 것 같습니다.
path variable이 숫자로 표현되는 이슈라는게 정확히 어떤 상황인지 구체적으로 알려주실 수 있으실까요?

2024-09-17 13:17 UTC, hun-cloud commented
> 잘 작성해주신 것 같습니다. path variable이 숫자로 표현되는 이슈라는게 정확히 어떤 상황인지 구체적으로 알려주실 수 있으실까요?

![image](https://github.com/user-attachments/assets/51368650-793c-421a-bf8a-e81ed37d2b79)
/api/v1/products/1 -> /api/v1/products/{productId}
저번에 호준님이 라이브 코딩 때 보여주셨던 코드에는 {productId} 이렇게 표현되었던 걸로 기억해서 여쭈어봤습니다!

2024-09-17 13:46 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductRepositoryImpl.kt
> +            ).where(
where부터 apply까지의 줄을 아래와 같이 수정하는 게 훨씬 좋아보입니다.
```kotlin
).whereAnd(
    searchWord?.let { path(ProductJpaEntity::title).like("%$searchWord%") },
    categoryId?.let { path(ProductJpaEntity::categoryId).eq(categoryId) }
)
```

1. let 구문을 통해 코드 가독성 및 불필요 where문 제거
  - searchWord가 매번 ""로 like 타게 되면 불필요한 where 쿼리가 생성되어 성능에 문제를 일으킬 것으로 보입니다.
  - kotlinJdsl 내부 where를 확인해 보니 Predicate가 null이 아니면 알아서 쿼리를 만들지 않는 것으로 확인하였고, let을 통해 null이 아닐 때만 쿼리를 생성하고 null이면 알아서 null 리턴.
2. kotlin에서는 $ 기호를 통해 문자열 통합이 가능
  - `"%" + (searchWord) + "%"` 보다는 `"%$searchWord%"` 이 가독성이 더 좋죠?
3. where문 안에 여러 개를 넣을 수 있도록 whereAnd와 whereOr 문을 지원해주니, 안 쓸 이유는 없을 것 같습니다

2024-09-17 14:12 UTC, psh10066 commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/ProductController.kt
>          return CommonResponse.ok(productUseCase.getProducts(request.toQuery()))
지금 보니까 이 API는 페이징으로 보이는데요,
프론트에서 페이징 처리를 하려면 **최소한** 전체 Item의 개수 혹은 최대 몇 페이지까지 있는지에 대한 값이 있어야 합니다. 그래야 다음 페이지가 있는지 없는지, 몇 페이지까지 있는지 (다음 페이지가 있는지 등) 확인해서 구현할 수 있습니다.

2024-09-17 14:12 UTC, psh10066 commented
> > 잘 작성해주신 것 같습니다. path variable이 숫자로 표현되는 이슈라는게 정확히 어떤 상황인지 구체적으로 알려주실 수 있으실까요?
> 
> ![image](https://private-user-images.githubusercontent.com/89080095/368180706-51368650-793c-421a-bf8a-e81ed37d2b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODI2MjYsIm5iZiI6MTcyNjU4MjMyNiwicGF0aCI6Ii84OTA4MDA5NS8zNjgxODA3MDYtNTEzNjg2NTAtNzkzYy00MjFhLWJmOGEtZTgxZWQzN2QyYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYWE0ZjViOTVjNTAzODNkZDk2ZWYxNzc5MDMxOGY4MGU0ZmU2MGMxNzg3MDg4M2ZiZTk5YzUwMzNlMmVjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X6KjWoPsedX6oAyNueF0A-lVsQ89e0qTSCP2Qs9Agzg) /api/v1/products/1 -> /api/v1/products/{productId} 저번에 호준님이 라이브 코딩 때 보여주셨던 코드에는 {productId} 이렇게 표현되었던 걸로 기억해서 여쭈어봤습니다!

아하 아니에요! 저렇게 예시 값이 뜨는 게 정상입니다~

2024-09-17 16:03 UTC, psh10066 requested changes
코멘트로 남긴 부분들 확인 부탁드립니다~

2024-09-18 02:33 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductRepositoryImpl.kt
> +            ).where(
감사합니다 적용하겠습니다!

2024-09-18 05:13 UTC, psh10066 requested changes

2024-09-18 05:13 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductRepositoryImpl.kt
> +            (totalCount / size).toInt()
totalPage 계산식이라면 여기에 +1이 빠진 것 같습니다.

그런데, 보통 이런식으로 if else 하기 보다는 아래처럼 ceil을 통해 올림 처리하는 걸 주로 사용합니다. 동일한 동작인데 가독성이 좋겠죠?
```kotlin
val totalPage = ceil(totalCount.toDouble() / size)
```

2024-09-18 11:58 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductRepositoryImpl.kt
> +            (totalCount / size).toInt()
앗 그렇네요! 1도 빠지고 ceil이 더 좋은 방법 같아요 감사합니다 :)

2024-09-18 12:43 UTC, psh10066 approved these changes

2024-09-19 10:21 UTC, merged