#14 서비스 - 주문 생성 기능 개발
FC-InnerCircle/icd01-team05_06-commerce-be pull request #25
Opened 2024-10-05 07:06 UTC by hyunolike

### 주요 개발 사항
- 주문 생성 기본 기능 개발 완료 (결제, 배송 제외)

### 기타 사항
- 주문 목록 조회 API 잘못된 데이터명 수정 (향기님 요청사항)

2024-10-05 07:08 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +    }
복잡한 로직을 Handler 클래스 내부에 넣어서 서비스 레벨에서는 추상화하여 도메인 언어로 가독성있게 코드를 구성했습니다.

2024-10-05 08:00 UTC, psh10066 requested changes

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +        productHandler.isAvailableProducts(products, request.products)
없는 경우에 대한 확인인 경우 is보다는 check나 valid 등의 워딩을 쓰는게 좋을 것 같습니다. (개인적으로는 check가 좋아보입니다)
is의 경우는 boolean으로 return되는 것 같은 느낌을 강하게 받습니다.

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +    }
방향성은 생각하신 대로 가는 게 맞습니다!
다만 클린 아키텍처 관점에서, 인터페이스는 기존처럼 application 레이어 안에 속하도록 하고 impl같은 세부적인 구현은 infrastructure같은 새로운 레이어 패키지를 만들어서 보관하면 더 좋을 것 같아요.
그렇게 되었을 때, 세부 구현이 바뀌게 되어도 application 레이어는 건드릴 필요가 없어지는 효과가 있습니다.

이러한 구조가 제가 추천드렸던 지속 가능한 설계의 레이어와 부합하는 면이 있습니다.

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/OrderUseCase.kt
> +    fun order(requets: OrderCreateRequest, member: Member) : OrderCreateResponse
단방향 의존성을 제대로 지키려면 사실 application 패키지에서는 controller의 패키지를 참조해서는 안됩니다.
(쉽게는 Request, Response 객체를 사용해서는 안된다는 뜻이에요)
이를 위해 요청 쪽에서는 command 객체를 따로 두고 매핑하고,
응답 쪽에서는 도메인 모델을 그대로 내려둔 후 controller에서 응답에 맞도록 매핑하는 방식이 보편적인 것 같아요.

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/component/ProductHandlerImpl.kt
> +    override fun getProducts(productIds: Any): List<Product> {
동일한 필드를 두고, 단 건 혹은 여러 건을 받기 위해 Any로 타입을 지정하는 건 좋지 않은 것 같습니다.
일단 여기는 List<Long> 필드로 고정해 두는 게 여러모로 장점이 있을 것 같고,
하나만 조회하는 경우면 그냥 item을 하나만 넣어주도록 하거나 아니면 따로 메서드를 빼거나 하는 게 좋아보입니다.

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +                productHandler.updateStock(order)
동시에 동일한 상품에 대해 주문이 들어왔을 때 재고 수량에 대한 동시성 처리, 주문이 어쩌다 실패했을 때의 롤백에 대해서 테스트가 잘 이루어져야 할 것 같습니다. 지금은 동시성 처리나 롤백 부분에 대해서 약점이 있는 것 같아요.

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/component/ProductHandlerImpl.kt
> +        // 주문 완료 응답 생성
이런 경우에도 application 레이어는 controller를 모른다고 한다면,
OrdersDTO를 그대로 return하고, 컨트롤러에서 Response를 매핑해주도록 구현하면 쉽게 의존 방향을 지킬 수 있을 것 같습니다.

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderCreateRequest.kt
> +    override fun validate() {
혹시 spring bean validation으로 어노테이션 기반 validation을 선호하지 않고 이렇게 직접 작성하는 것을 선호하시나요?

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderCreateRequest.kt
> +) : CommonRequest {
controller에서 항상 validate() 메서드를 직접 호출하는 것으로 보이는데,
이건 누락될 위험도 있고 해서 개인적으로는 여기 안에다가 init 블럭을 추가한 후 init에서 validate()를 수행하면 어떨까 싶네용

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/vo/OrderNumber.kt
> +            return OrderNumber("ORD-${LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"))}-${(100..999).random()}")
동일한 날짜에 주문하면 겹칠 우려가 있지 않을까요?

2024-10-05 08:00 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/component/ProductHandlerImpl.kt
> +        ordersRepository.save(order.toOrder())
orderProduct를 저장하고 있는게 맞나요?
orderProductRepository.save()를 호출하지 않고 있는 것 같습니다.

2024-10-05 08:00 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        deletedAt = LocalDateTime.now(),
deletedAt은 soft delete의 분기 컬럼으로, 삭제되었을 때에만 추가하는 필드입니다.
해당 필드에 값이 있으면 해당 row는 없음 취급하는거에요. 매핑 시에는 추가되어서는 안됩니다.

2024-10-05 08:00 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        createdAt = LocalDateTime.now(),
createdAt에 대한 매핑 시 now를 추가해줘서는 안됩니다.
그렇게 되면 수정 시에도 createdAt 필드가 같이 업데이트되어버리는 문제가 발생할 것 같아요.

createdAt, updatedAt같은 필드들은 매핑 자체가 안이루어지게 하는게 가장 좋을 것 같고,
이를 위해서 BaseTimeEntity를 만들어서 사용하도록 했으니 해당 클래스를 extend하여 사용해 주세요!

2024-10-05 08:09 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +    }
> 방향성은 생각하신 대로 가는 게 맞습니다! 다만 클린 아키텍처 관점에서, 인터페이스는 기존처럼 application 레이어 안에 속하도록 하고 impl같은 세부적인 구현은 infrastructure같은 새로운 레이어 패키지를 만들어서 보관하면 더 좋을 것 같아요. 그렇게 되었을 때, 세부 구현이 바뀌게 되어도 application 레이어는 건드릴 필요가 없어지는 효과가 있습니다.
> 
> 이러한 구조가 제가 추천드렸던 지속 가능한 설계의 레이어와 부합하는 면이 있습니다.

앗 감사합니다! 말씀하신데로 새로운 패키지 만들어서 구현되도록 하겠습니다 👍

2024-10-05 08:10 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +        productHandler.isAvailableProducts(products, request.products)
> 없는 경우에 대한 확인인 경우 is보다는 check나 valid 등의 워딩을 쓰는게 좋을 것 같습니다. (개인적으로는 check가 좋아보입니다) is의 경우는 boolean으로 return되는 것 같은 느낌을 강하게 받습니다.

수정하겠습니다! 느낌그대로 네이밍한거라 ㅎ

2024-10-05 08:11 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/OrderUseCase.kt
> +    fun order(requets: OrderCreateRequest, member: Member) : OrderCreateResponse
> 단방향 의존성을 제대로 지키려면 사실 application 패키지에서는 controller의 패키지를 참조해서는 안됩니다. (쉽게는 Request, Response 객체를 사용해서는 안된다는 뜻이에요) 이를 위해 요청 쪽에서는 command 객체를 따로 두고 매핑하고, 응답 쪽에서는 도메인 모델을 그대로 내려둔 후 controller에서 응답에 맞도록 매핑하는 방식이 보편적인 것 같아요.

맞아요! 수정진행하겠습니다!

2024-10-05 08:12 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/component/ProductHandlerImpl.kt
> +    override fun getProducts(productIds: Any): List<Product> {
> 동일한 필드를 두고, 단 건 혹은 여러 건을 받기 위해 Any로 타입을 지정하는 건 좋지 않은 것 같습니다. 일단 여기는 List 필드로 고정해 두는 게 여러모로 장점이 있을 것 같고, 하나만 조회하는 경우면 그냥 item을 하나만 넣어주도록 하거나 아니면 따로 메서드를 빼거나 하는 게 좋아보입니다.

이거 고민했었는데 Any 타입말고 다른 방향으로 구성해보겠습니다!

2024-10-05 08:14 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +                productHandler.updateStock(order)
> 동시에 동일한 상품에 대해 주문이 들어왔을 때 재고 수량에 대한 동시성 처리, 주문이 어쩌다 실패했을 때의 롤백에 대해서 테스트가 잘 이루어져야 할 것 같습니다. 지금은 동시성 처리나 롤백 부분에 대해서 약점이 있는 것 같아요.

네 아직 동시성 처리 이런부분은 진행하지 못해서 주요 리뷰 사항 수정이후 진행해보겠습니다!

2024-10-05 08:14 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderCreateRequest.kt
> +) : CommonRequest {
> controller에서 항상 validate() 메서드를 직접 호출하는 것으로 보이는데, 이건 누락될 위험도 있고 해서 개인적으로는 여기 안에다가 init 블럭을 추가한 후 init에서 validate()를 수행하면 어떨까 싶네용

앗 맞아요 뭔가 공통적으로 한거긴 한건데 수정해서 진행해보겠습니다!

2024-10-05 08:15 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/vo/OrderNumber.kt
> +            return OrderNumber("ORD-${LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"))}-${(100..999).random()}")
> 동일한 날짜에 주문하면 겹칠 우려가 있지 않을까요?

고려해서 수정해보겠습니다!

2024-10-05 08:18 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/component/ProductHandlerImpl.kt
> +        ordersRepository.save(order.toOrder())
> orderProduct를 저장하고 있는게 맞나요? orderProductRepository.save()를 호출하지 않고 있는 것 같습니다.

아 이거 save() 만들고 써야지 했는데 알고보니 연관관계 맺어있어서 자동 저장이 되버리고 있..ㅎㅎㅎㅎ

```kt
@OneToMany(mappedBy = "order", cascade = [CascadeType.ALL], orphanRemoval = true)
    val orderProducts: MutableList<OrderProductJpaEntity> = mutableListOf()
```

2024-10-05 08:19 UTC, hyunolike commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        deletedAt = LocalDateTime.now(),
> deletedAt은 soft delete의 분기 컬럼으로, 삭제되었을 때에만 추가하는 필드입니다. 해당 필드에 값이 있으면 해당 row는 없음 취급하는거에요. 매핑 시에는 추가되어서는 안됩니다.

네 수정하겠습니다!

2024-10-05 08:19 UTC, hyunolike commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        createdAt = LocalDateTime.now(),
> createdAt에 대한 매핑 시 now를 추가해줘서는 안됩니다. 그렇게 되면 수정 시에도 createdAt 필드가 같이 업데이트되어버리는 문제가 발생할 것 같아요.
> 
> createdAt, updatedAt같은 필드들은 매핑 자체가 안이루어지게 하는게 가장 좋을 것 같고, 이를 위해서 BaseTimeEntity를 만들어서 사용하도록 했으니 해당 클래스를 extend하여 사용해 주세요!

네 확인해서 수정하겠습니다!

2024-10-05 11:25 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/component/ProductHandlerImpl.kt
> +        ordersRepository.save(order.toOrder())
아 이미 자동 저장되고 있는거면 괜찮습니다~

2024-10-07 13:20 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +    }
infrastructure 명으로 새로운 패키지 만들어서 impl 구현 파일들 보관했습니다.

<img width="313" alt="image" src="https://github.com/user-attachments/assets/bbc81859-b853-40c6-8f1a-948444b86be9">

2024-10-07 13:21 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +        productHandler.isAvailableProducts(products, request.products)
```kotlin
        // 2. 상품이 존재하지 않거나 재고가 부족한 경우(다수의 상품을 한번에 확인)
        productHandler.checkAvailableProducts(products, command.products)
```

네이밍 변경해서 수정 완료했습니다.

2024-10-07 13:28 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/OrderUseCase.kt
> +    fun order(requets: OrderCreateRequest, member: Member) : OrderCreateResponse
```kt
    // 주문 조회 API
    @GetMapping
    fun getOrder(@Validated request: OrderListRequest,  @AuthenticationPrincipal member: Member): ResponseEntity<CommonResponse<OrderListResponse>> {
        val response = orderUseCase.getOrder(request.toCommand(member))
        return ResponseEntity.ok(CommonResponse.ok(data = response))
    }
    
        // 주문 생성 API
    @PostMapping
    fun createOrder(@Valid @RequestBody request: OrderCreateRequest, @AuthenticationPrincipal member: Member): ResponseEntity<CommonResponse<OrderCreateResponse>> {
        val response = orderUseCase.order(request.toCommand(member))
        return ResponseEntity.ok(CommonResponse.ok(data = response))
    }
}
```

command 객체 추가 및 요청값 검증 init 처리 했습니다.

2024-10-07 13:29 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/component/ProductHandlerImpl.kt
> +    override fun getProducts(productIds: Any): List<Product> {
List 필드로 고정했습니다

```Kotlin
    // 상품 정보 조회
    override fun getProducts(productIds: List<Long>): List<Product> {
        return productIds.map { productId ->
            productRepository.findById(productId)
                ?: throw ProductNotFoundException(productId)
        }
    }
```

2024-10-07 13:29 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +                productHandler.updateStock(order)
이 부분은 고도화 과정에서 진행해도 될까요? ㅠ

2024-10-07 13:31 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderCreateRequest.kt
> +) : CommonRequest {
```kotlin
    init {
        validate()
    }

    override fun validate() {
        products.forEach {
            if (it.id <= 0) {
                throw InvalidInputException("Invalid product id: ${it.id}")
            }
            if (it.quantity <= 0) {
                throw InvalidInputException("Invalid product quantity: ${it.quantity}")
            }
        }
        
        ...
```
command 객체 추가 및 요청값 검증 init 처리 했습니다.

2024-10-07 13:32 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/vo/OrderNumber.kt
> +            return OrderNumber("ORD-${LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"))}-${(100..999).random()}")
```kotlin
        // 실제 주문 번호 생성
        // 주문번호는 ("ORD-20240815-000001") 이와 같이 "ORD-날짜-6자리순차번호" 형태로 생성된다.
        fun createOrderNumber(): OrderNumber {
            checkAndResetCounterIfNeeded()
            val date = LocalDate.now().format(dateFormatter)
            val sequence = counter.incrementAndGet().toString().padStart(6, '0')
            return OrderNumber("ORD-$date-$sequence")
        }
```

ORD-날짜-6자리순차번호로 생성하게끔 해서 동일한 날짜 겹치지 않도록 수정했습니다.

2024-10-07 13:33 UTC, hyunolike commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        deletedAt = LocalDateTime.now(),
재훈님이 담당하는 모듈이여서 수정진행하지 않았습니다! (겹칠거 같아요)

2024-10-07 13:33 UTC, hyunolike commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        createdAt = LocalDateTime.now(),
재훈님이 담당하는 모듈이여서 수정진행하지 않았습니다! (겹칠거 같아요)

2024-10-07 16:04 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +                productHandler.updateStock(order)
네네 그럼요~

2024-10-07 16:19 UTC, psh10066 requested changes

2024-10-07 16:19 UTC, psh10066 commented on commerce-service/commerce-auth/src/main/kotlin/com/commerce/service/auth/application/usecase/command/LoginCommand.kt
> +    data class ProductInfo(
여기 inner class 4개는 안쓰는 것 같은데, 안쓰는 코드들은 잘 확인해서 항상 지워주세요!

2024-10-07 16:19 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/application/usecase/OrderUseCase.kt
> +    fun order(command: CreateOrderCommand) : OrderCreateResponse
application 패키지 내에서 Response를 내려주는 것 자체가 Controller 관련 레이어를 알게 되는 문제가 있긴 한데요,
이 부분은 이번 리뷰 이후에 제가 소개드린 ArchUnit 도입하시면서 한번에 고쳐보시면 어떨까 싶네용

2024-10-07 16:19 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/application/usecase/vo/OrderNumber.kt
> +        private val counter = AtomicLong(0)
이걸로 순차 번호를 사용하게 되면 아래와 같은 문제가 있습니다.

- 서버가 배포되면 0으로 초기화된다.
- 동일한 Application을 여러 개 띄우고 로드 밸런서로 잡는 경우 둘다 0부터 시작해서 무조건 겹친다.

따라서 순차 번호를 사용하려면 결국 무조건 DB를 거치긴 해야 합니다.
이 부분은 일단 놔두고 추후에 Redis로 제가 한번 손봐볼게요!

2024-10-07 16:19 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderCreateRequest.kt
> +    override fun validate() {
@hyunolike 위 댓글 확인 부탁드려용

2024-10-07 16:19 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        deletedAt = LocalDateTime.now(),
아하 아마 이런 부분들은 Rebase가 잘못되거나 해서 이력에 남아버린 것 같네요

2024-10-07 16:19 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        createdAt = LocalDateTime.now(),
아하 아마 이런 부분들은 Rebase가 잘못되거나 해서 이력에 남아버린 것 같네요

2024-10-07 16:27 UTC, psh10066 commented
applicaton -> application 패키지 명 변경, 향기님 요청으로 API 필드 오타 수정 등은 해당 PR인 "주문 생성 기능 개발"과는 관련이 없습니다.
관련이 없는 내용들은 항상 잘게 쪼개서 다른 브랜치에서 작업하고 PR도 따로 관리하는 것이 좋아요.
혼자 작업하는 경우는 마음대로 해도 상관없지만, 협업 시에는 이력 관리가 힘들고 PR 리뷰도 힘들어지는 문제가 있어요.

2024-10-07 23:20 UTC, hyunolike commented
> applicaton -> application 패키지 명 변경, 향기님 요청으로 API 필드 오타 수정 등은 해당 PR인 "주문 생성 기능 개발"과는 관련이 없습니다.
> 
> 관련이 없는 내용들은 항상 잘게 쪼개서 다른 브랜치에서 작업하고 PR도 따로 관리하는 것이 좋아요.
> 
> 혼자 작업하는 경우는 마음대로 해도 상관없지만, 협업 시에는 이력 관리가 힘들고 PR 리뷰도 힘들어지는 문제가 있어요.

아하! 감사합니다! 신경써서 쪼개서 관리하겠습니다

2024-10-07 23:24 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/application/usecase/OrderUseCase.kt
> +    fun order(command: CreateOrderCommand) : OrderCreateResponse
앗 거기까지 생각을 못했네요ㅠ 감사합니다! 도입해서 수정하겠습니다!

2024-10-07 23:26 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/application/usecase/vo/OrderNumber.kt
> +        private val counter = AtomicLong(0)
아아아아 거기까지 생각을 못했...ㅎ
감사합니다! 저도 다시 살펴보겠습니다

2024-10-07 23:28 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderCreateRequest.kt
> +    override fun validate() {
앗 그걸로 수정하겠습니다! 선호하는건 아니에요 그게 있다는걸 지금에서 알았어요ㅠ

2024-10-07 23:36 UTC, hyunolike commented on commerce-service/commerce-auth/src/main/kotlin/com/commerce/service/auth/application/usecase/command/LoginCommand.kt
> +    data class ProductInfo(
어쩐지 넣었는데 동작이 안되더라구요ㅋㅋㅋㅋㅋ왜 거기에다 넣었지.. 😱😱삭제하겠습니다!

CreateOrderCommand 여기다 넣어서 사용하려고 했어요ㅠ


```kotlin

 fun toCommand(member: Member) = CreateOrderCommand(
        member = member,
        products = products.map { CreateOrderCommand.ProductInfo(it.id, it.quantity) },
        deliveryInfo = CreateOrderCommand.DeliveryInfo(
            deliveryInfo.recipient,
            deliveryInfo.phoneNumber,
            deliveryInfo.email,
            deliveryInfo.streetAddress,
            deliveryInfo.detailAddress,
            deliveryInfo.postalCode
        ),
        paymentInfo = CreateOrderCommand.PaymentInfo(
            paymentInfo.method,
            paymentInfo.totalAmount,
            paymentInfo.depositorName
        ),
        agreementInfo = CreateOrderCommand.AgreementInfo(
            agreementInfo.termsOfService,
            agreementInfo.privacyPolicy,
            agreementInfo.ageVerification
        )
    )

```

2024-10-07 23:38 UTC, hyunolike commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/product/ProductJpaEntity.kt
> +        createdAt = LocalDateTime.now(),
맞아요 리베이스 뭔가 저번에 한번 했는데 코드가 사라져서 당황했던적이 많아요ㅠ 깃 공부 더 해야겠다

2024-10-08 11:15 UTC, hyunolike commented
@psh10066 
2차 코드 리뷰 사항

1. 불필요한 inner class 제거
2. spring validation 적용
3. 리베이스 이후 product 누락 코드 추가

2024-10-08 11:16 UTC, hyunolike commented
뭔가 리베이스를 했는데 ㅋㅋㅋㅋㅋ 하나의 커밋에 많이 들어갔..네요..ㅎ @psh10066

2024-10-08 11:21 UTC, psh10066 approved these changes

2024-10-08 11:24 UTC, merged