Feature/#5
FC-InnerCircle/icd01-team05_06-commerce-be pull request #27
Opened 2024-10-05 16:12 UTC by hun-cloud

상품 상세 - 리뷰  보여주기, 상품 상세 - 리뷰 등록 API 개발

2024-10-06 07:58 UTC, psh10066 requested changes

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/request/ReviewCreateRequest.kt
> +    val email: String,
이렇게 구성하게 되면 프론트에서 email을 잘 가지고 있어야 하는 문제가 있고, 본인이 아닌 다른 이메일로도 작성할 수 있는 문제가 있습니다.
로그인한 유저 본인만 리뷰를 작성할 수 있어야 하기 때문에, 다른 모듈처럼 Spring Security 의존성을 추가하고 JWT 토큰 받아서 Member를 직접 가져오도록 구성하는 게 좋습니다.

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/test/kotlin/com/commerce/service/product/controller/ReviewControllerTest.kt
> +                        fieldWithPath("orderProductId").type(JsonFieldType.NUMBER).optional().description("주문 - 상푸 리뷰"),
description에 상품 오타가 있네용

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/ReviewController.kt
> +                updatedAt = it.updatedAt,
저는 updatedAt을 사용자에게 보여지도록 구성하는 걸 선호하지 않습니다.
기본적으로 createdAt 필드와 updatedAt 필드는 DB의 해당 row가 언제 생성되고 언제 수정되었는지를 나타내는 필드인데요,
사용자가 수정하지 않더라도 해당 row가 수정이 되면 자동으로 해당 시각으로 updatedAt 필드가 업데이트되어버리는 문제가 있습니다.

여기서 return해주려고 하는 필드는 "작성자가 최종 수정한 시각" 인데요,
만약 관리자가 리뷰 상태를 관리하고 수정할 수 있다고 생각해 봅시다.
관리자가 해당 리뷰의 상태를 일부 공개 리뷰에서 전체 공개 리뷰로 바꾼다면 해당 row의 리뷰 상태 컬럼이 수정되므로 updatedAt이 최신화되어버리는 문제가 있습니다.

createdAt은 최초 생성되고 나서 수정될 일이 없어서 최초 생성시각 기준으로는 사용해도 괜찮다고 생각하지만,
위와 같은 이유로 updatedAt 필드는 return해주지 않는 것을 권장합니다.
리뷰 최종 수정 시각에 관련된 필드를 따로 두고 관리해주시는 방향이 좋을 것 같아요.

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/ReviewController.kt
> +    // 상품 전체 평점 select
추후에 추가하기 위한 용도로 작성한 주석이라면
// TODO : 상품 전체 평점 select
와 같이 해주는 게 좋을 것 같고, 아니라면 제거하는 것이 좋아보입니다.

2024-10-06 07:58 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/review/ReviewJpaRepository.kt
> +    fun findByProductId(productId: Long): Optional<List<ReviewJpaEntity>>
kotlin에서는 타입에서 null 체크가 가능하기 때문에 Optional을 사용하지 않는 걸 권장합니다.
또한 JPA 쿼리 메서드의 return type을 List로 받아오게 되면 nulll은 어차피 발생할 일이 없습니다. 해당하는 row가 하나도 없다면 빈 List가 반환될 거에요.
따라서 단순히 List<ReviewJpaEntity> 를 반환 타입으로 사용해 주시는게 좋을 것 같습니다.

2024-10-06 07:58 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/review/ReviewJpaRepository.kt
> +    fun findByProductId(productId: Long): Optional<List<ReviewJpaEntity>>
그런데 자세히 보니까 해당 메서드 자체를 사용하고 있지 않아 보이네요?
불필요한 메서드라면 지우는 게 좋아보입니다.

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/test/kotlin/com/commerce/service/product/controller/ReviewControllerTest.kt
> +                        fieldWithPath("orderProductId").type(JsonFieldType.NUMBER).optional().description("주문 - 상푸 리뷰"),
또한 해당 필드는 언제 null이고, 언제 null이 아닌지에 대해 프론트 개발자가 알고 사용할 수 있도록 설명을 추가해 주는 것이 좋아보입니다.

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/application/service/ReviewService.kt
> +            orderProductId = addReviewCommand.orderProductId
저번에 설명드렸을 때 orderProductId가 존재하는 경우는 주문(order) 기준으로 리뷰를 작성할 때이고,
null인 경우는 상품 페이지에서 리뷰를 작성할 때로 정의했었습니다.

만약 두 경우의 리뷰 등록 API를 같이 사용할 것이라면, 주문의 리뷰와 상품의 리뷰 둘 다 해당 메서드를 사용할 것이기 때문에 byProduct라는 워딩 자체가 맞지 않을 것 같습니다.
만약 두 경우의 리뷰 등록 API를 따로 사용할 것이라면, byProduct의 orderProductId 파라미터 및 API request에서도 해당 필드를 받지 않고 알아서 null로 등록되도록 처리해줘야 할 것 같아요.

현재는 첫 번째 경우로 개발된 것 같으니,
request API 명세에서 해당 필드에 대해 상세히 작성해 주고, byProduct의 메서드명을 add나 create 등 다른 것으로 바꾸는게 좋아보입니다. (메서드명에서 리뷰를 생성하기 위한 메서드라는 것을 명확히 해주는 게 좋습니다.)

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/test/kotlin/com/commerce/service/product/application/service/ReviewServiceTest.kt
> +        reviewRepository = FakeReviewRepository(memberRepository)
FakeReviewRepository가 MemberRepository를 의존하는 것에 대해 좋은 아이디어인지 고민을 좀 해봤는데요,
실제로도 결국 Member 테이블에서 데이터를 join해서 가져오는 것이다 보니 아래에 작성해주신 대로 테스트를 작성해주신 게 더 직관적이라는 생각이 드네요. 잘 구현해주신 것 같습니다 👍

2024-10-06 07:58 UTC, psh10066 commented on commerce-service/commerce-product/src/docs/asciidoc/product-api-guide.adoc
> +=== Response
해당 API는 query parameter가 존재하는 만큼 Request 블록이 추가되어야 할 것으로 보입니다.

2024-10-07 10:04 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/request/ReviewCreateRequest.kt
> +    val email: String,
아 멘토님과도 얘기 했던 내용인데 제가 까먹고 있었네요 ! 네 Spring Security 의존성 추가하고 작업하도록 하겠습니다 :)

2024-10-07 10:10 UTC, hun-cloud commented on commerce-service/commerce-product/src/test/kotlin/com/commerce/service/product/controller/ReviewControllerTest.kt
> +                        fieldWithPath("orderProductId").type(JsonFieldType.NUMBER).optional().description("주문 - 상푸 리뷰"),
네 desciptoin 더 보충하겠습니다!

2024-10-07 10:14 UTC, hun-cloud commented on commerce-service/commerce-product/src/test/kotlin/com/commerce/service/product/application/service/ReviewServiceTest.kt
> +        reviewRepository = FakeReviewRepository(memberRepository)
감사합니다 !

2024-10-07 10:14 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/ReviewController.kt
> +    // 상품 전체 평점 select
네네 지우도록 할게요!

2024-10-07 10:17 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/ReviewController.kt
> +                updatedAt = it.updatedAt,
좋은 생각인 것 같습니다! 컬럼 하나 더 추가할게요!

2024-10-07 10:22 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/application/service/ReviewService.kt
> +            orderProductId = addReviewCommand.orderProductId
섬세한 리뷰 감사드립니다!

2024-10-07 10:22 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/review/ReviewJpaRepository.kt
> +    fun findByProductId(productId: Long): Optional<List<ReviewJpaEntity>>
넵 확인해볼게요!

2024-10-07 10:23 UTC, hun-cloud commented on commerce-service/commerce-product/src/docs/asciidoc/product-api-guide.adoc
> +=== Response
네 감사합니다!

2024-10-09 11:37 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/application/service/ReviewService.kt
> +            orderProductId = addReviewCommand.orderProductId
고민을 해보았는데
상품 리뷰와 구매 리뷰와는 분리하는게 어떨까 싶습니다.
추후에 구매 리뷰에는 포인트를 준다든지의 로직이 추가될 수 있다고 생각이 듭니다.
어떻게 생각하실까요 ?

2024-10-10 10:17 UTC, psh10066 approved these changes

2024-10-10 10:17 UTC, merged