#7 서비스 - 주문 기능 개발
FC-InnerCircle/icd01-team05_06-commerce-be pull request #8
Opened 2024-09-02 14:11 UTC by hyunolike

## 서비스 - 주문 기능 API 
- 09.02 기준. 주문 목록 조회 (날짜 조건 제외) 개발 완료
- 추가 개발 필요 . 주문 상세 조회

## 참고사항
- 코드 정리 필요
- 인증 서비스에 맞춰 코드 정리 필요 ...ㅎ 다급하게 마무리..

아직 이슈는 못닫아요..ㅎ (추가 개발 필요)

2024-09-02 14:14 UTC, hyunolike commented on build.gradle.kts
> +
이 부분은 컴파일 빌드 이슈가 나서 코드 넣은거에요!
저만 에러가 나는걸까요..?ㅎ

2024-09-02 14:15 UTC, hyunolike commented on build.gradle.kts
> +
이 부분은 컴파일 빌드 이슈가 나서 코드 넣은거에요!
저만 에러가 나는걸까요..?ㅎ

2024-09-02 15:17 UTC, psh10066 requested changes
일단 제대로 로직을 파악하기 전에 눈에 보이는 부분만 간략하게 리뷰 드렸습니다.
시간 있을 때마다 현재 코드에서 추가적으로 리뷰 사항 있으면 남겨드릴 테니, 일단 먼저 기입한 내용대로 확인 및 작업 부탁드려요!

2024-09-02 15:17 UTC, psh10066 commented on commerce-service/commerce-order/READMD.md
README인데 READMD로 오타가 나있네요 ㅎㅎ

2024-09-02 15:17 UTC, psh10066 commented on build.gradle.kts
> +
음 일단 바로 윗줄에 `jvmTarget.set(JvmTarget.JVM_21)` 구문이 있기도 하고,
제 환경에서는 컴파일이 잘 되는 것으로 보아 IntelliJ 설정 문제가 아닐까 싶습니다.
이 부분은 화면 공유해서 확인해보면 좋을 것 같아요!

2024-09-02 15:17 UTC, psh10066 commented on commerce-service/commerce-order/build.gradle.kts
> +        into(layout.projectDirectory.dir("src/main/resources/static/docs"))
이게 `src/main/resources`로 들어가면 저희가 건드리는 코드에 계속 수정사항이 발생해서 git에 올려줘야 하는 문제가 있습니다.
그리고 지금 보면 "static/docs"로 들어갔다가 "src/main/resources/static/docs"로 들어가는, 복사를 두번 하는 느낌이 들어요.

commerce-auth의 build.gradle을 참고해 보시면
"build/resources/main/static/docs" 경로로 html 파일을 삽입하게 되어 빌드 후 실행하면 html 파일이 똑같이 뜨지만, src 폴더를 건드리지 않습니다.
또한 조금 더 간단한 명령어로 되어있는 것 같아서, commerce-auth의 build.gradle을 참고하여 구성해 보시면 좋을 것 같아요.

2024-09-02 15:17 UTC, psh10066 commented on commerce-service/commerce-order/src/docs/asciidoc/order-api-guide.adoc
잘 몰라서 그러는데 여기의 모든 내용을 직접 작성하신 걸까요? 아니면 이런 포맷으로 자동으로 만들어지는 걸까요?

전자라면, restdocs는 테스트 성공 후의 snippet들을 자동으로 생성해주기 때문에 그에 맞게 Include하도록 구성하는 게 자동화에 더 좋을 것 같습니다. auth-api-guide.adoc를 참고해 보시면 좋을 것 같아요.
후자라면, 내용은 저도 몰라서 공유해주시면 좋을 것 같습니다.

2024-09-02 15:17 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +        return when (range) {
when 문에서 작업하는 것보다 DateRange 내에서 abstract 메서드를 만들어서 각 타입에서 Override하여 구성하면 훨씬 깔끔할 것 같습니다.

2024-09-02 15:17 UTC, psh10066 commented on commons/model/build.gradle.kts
> +    implementation(project(":commons:persistence-database"))
model에서는 persistence-database를 참조하면 안됩니다.
일단, 이미 persistence-database는 model을 의존하고 있기 때문에 서로 모듈을 순환 의존하는 문제가 발생해요.
그리고 저희 프로젝트의 단방향 의존 방향에서는 model은 persistence (DB) 관련 내용을 몰라야 합니다.

현재 이 의존을 빼게 되면 Pageable, Page를 가질 수 없는 문제는 간단하게 `implementation("org.springframework.boot:spring-boot-starter-data-jpa")` 로 바꾸어 해결할 수 있는데요, 좋은 방법인지는 잘 모르겠습니다.
제 욕심으로는 Pageable과 Page도 모르게 하고 싶긴 한데, 이걸 빼게 되면 너무 돌아가야 할 것 같아서 일단 이 의존성 추가로 해결해 봐도 괜찮을 것 같아요.

2024-09-02 15:17 UTC, psh10066 commented on commerce-service/commerce-order/src/test/kotlin/com/commerce/service/order/controller/OrderControllerTest.kt
> +                    fieldWithPath("success").description("Whether the request was successful"),
여기의 fieldWithPath에 Optional 여부와 DataType 등을 설정할 수 있고, 그 내용이 snippet에 반영되기 떄문에 추가해주시면 좋을 것 같아요. 기타 다른 커스텀한 attribute도 선언이 가능한데, 이것도 auth를 참고해 보시면 도움이 되지 않을까 싶습니다.

2024-09-02 15:17 UTC, psh10066 commented on commerce-service/commerce-order/src/test/kotlin/com/commerce/service/order/controller/OrderControllerTest.kt
지금 테스트 코드 자체가 깨지고 있는 것으로 보아 최종본은 아닌 것 같습니다.
테스트 코드 정상화 및 build까지 잘 되도록만 먼저 수정 부탁드려요!

2024-09-02 18:00 UTC, YunNote commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +    override fun getOrder(request: OrderListRequest) : OrderListResponse {
Page관련 필드들에 대해서 Class로 분리하여 Pageable 을 반환하도록 개발해보는건 어떻게 생각하시나요 ?!

2024-09-02 18:00 UTC, YunNote commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/exception/GlobalExceptionHandler.kt
> +        val status = when (ex) {
status를 when식으로 받아서 val status로 저장하였으나 사용처가 없는듯합니다!
확인 부탁드리겠습니다

2024-09-02 18:00 UTC, YunNote commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderListRequest.kt
> +    enum class DateRange {
조회와 관련된 Enum들은 따로 파일로 분리하는건 어떻게 생각하세요 ?!

2024-09-02 18:00 UTC, YunNote commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/response/OrderListResponse.kt
> +)
추후에 totalElements와 totalPages를 반환하는 Response 들이 많아진다면 공통코드로 분리하여 제네릭으로 묶어보는것도 하나의 방법이 되지 않을까? 라고 생각하는데 어떻게 생각하시나요

2024-09-02 18:00 UTC, YunNote commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/order/OrderJpaEntity.kt
> +    val postalCode: String,
streetAddress, detailAddress, postalCode 주소와 관련된 내용으로 보여지는데 해당 내용 @Embedded 사용해보시는건 어떨까요 ?!

2024-09-02 18:00 UTC, YunNote commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/order/OrderJpaEntity.kt
> +    val createdAt: LocalDateTime = LocalDateTime.now(),
BaseEntity와 같이 JpaAuditing 을 사용한 등록은 어떻게 생각하시나요 ?!

2024-09-02 18:00 UTC, YunNote commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/order/OrderJpaEntity.kt
> +    enum class OrderStatus {
주문에 대한 상태 Enum도 별도의 Enum 으로 분리하는건 어떻게 생각하시나요 ?! 

해당 방법에 정답은 없으나 상태에 따른 검색등이 들어갔을때 OrderJpaEntity.OrderStatus를 통한 접근보다 OrderStatus로 접근하는것도 괜찮은 방법으로 보여지는데 어떻게 생각하시나요 ?!

2024-09-02 21:57 UTC, hyunolike commented
@YunNote @psh10066  코드리뷰 감사합니다! 퇴근하고 확인해서 수정하겠습니다 🔥🔥🔥

2024-09-03 03:03 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/order/OrderJpaEntity.kt
> +    val postalCode: String,
맞아요 이 부분은 저희 최초 도메인 설계할 때에도 Address라는 값 객체를 두고 Embedded로 할 계획이 있긴 했습니다.
다만 현재 협업 과정에서 공통적인 값 객체를 중복으로 생성하게 되는 이슈가 있을까 봐 당장은 도입하지는 않았는데, 추후 개선 예정으로 봐 주시면 좋을 것 같습니다~

2024-09-03 03:05 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/order/OrderJpaEntity.kt
> +    val createdAt: LocalDateTime = LocalDateTime.now(),
맞아요 Auditing으로 모두 개선할 예정이긴 합니다.
다만 현재 협업 과정에서 공통적인 객체를 중복으로 생성하게 되는 이슈가 있기도 하고, 재훈님이 Auditing 관련 클래스를 생성해 주셨으니, 해당 PR이 머지되고 나서 그 객체를 같이 사용하는 방향으로 가면 좋을 것 같습니다~

2024-09-03 10:57 UTC, hyunolike commented on commons/model/build.gradle.kts
> +    implementation(project(":commons:persistence-database"))
ㅋㅋㅋㅋ 지금 테스트 중인데..맞네요...ㅋㅋㅋ
<img width="590" alt="image" src="https://github.com/user-attachments/assets/6abf64bc-6e27-42d0-83b8-9a586be1acc2">

2024-09-03 11:01 UTC, hyunolike commented on build.gradle.kts
> +
삭제하니까 다시 떠요ㅠㅠ 해결해보겠습니다 🔥
<img width="837" alt="image" src="https://github.com/user-attachments/assets/c4473680-88ab-4171-a2fb-26517198d868">

2024-09-03 11:03 UTC, hyunolike commented on commerce-service/commerce-order/READMD.md
ㅠㅠ 휴먼에러..

2024-09-03 12:25 UTC, hyunolike commented on build.gradle.kts
> +
휴 ... 알고보니 제 맥북 자바 버전이 22 버전이였...ㅎ
인텔리제이상에서 해결하려했는데 전역적으로 적용되나봐요..
<img width="414" alt="image" src="https://github.com/user-attachments/assets/bd47eb29-a15b-4365-a141-3ab936e6260f">

2024-09-07 05:04 UTC, hyunolike commented on build.gradle.kts
> +
[수정사항 공유] 
위 코드 제거해서 수정했습니다. (로컬 자바 버전 이슈)

2024-09-07 05:04 UTC, hyunolike commented on commerce-service/commerce-order/READMD.md
[수정사항 공유] 
파일명 수정했습니다.

2024-09-07 05:05 UTC, hyunolike commented on commerce-service/commerce-order/build.gradle.kts
> +        into(layout.projectDirectory.dir("src/main/resources/static/docs"))
[수정사항 공유] 
위 코드 제거해서 인증 서비스와 동일하게 수정했습니다.

2024-09-07 05:05 UTC, hyunolike commented on commerce-service/commerce-order/src/docs/asciidoc/order-api-guide.adoc
[수정사항 공유] 
위 코드도 자동 생성되도록 수정했습니다.

2024-09-07 05:06 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +        return when (range) {
[수정사항 공유] 
이 부분은 추가 api 개발하면서 수정 진행하겠습니다.

2024-09-07 05:06 UTC, hyunolike commented on commons/model/build.gradle.kts
> +    implementation(project(":commons:persistence-database"))
[수정사항 공유] 
라이브러리 추가하는 방식으로 의존성 수정했습니다.

2024-09-07 05:09 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/usecase/exception/GlobalExceptionHandler.kt
> +        val status = when (ex) {
[수정사항 공유] 
status 연결해서 수정했습니다.

```kotlin
        return ResponseEntity
            .status(status)
            .body(CommonResponse(success = false, error = listOf(errorResponse)))
```

2024-09-07 05:10 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/request/OrderListRequest.kt
> +    enum class DateRange {
[수정사항 공유]
현재 진행 중인 모듈(인증, 주문, 상품) 개발 머지 후 고려해서 진행하겠습니다.

2024-09-07 05:10 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +    override fun getOrder(request: OrderListRequest) : OrderListResponse {
[수정사항 공유]
현재 진행 중인 모듈(인증, 주문, 상품) 개발 머지 후 고려해서 진행하겠습니다.

2024-09-07 05:11 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/controller/response/OrderListResponse.kt
> +)
[수정사항 공유]
좋은 생각 같습니다! 고려해서 진행하겠습니다.

2024-09-07 05:22 UTC, hyunolike commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/order/OrderJpaEntity.kt
> +    enum class OrderStatus {
[수정사항 공유]
좋은 생각같습니다!
분리해서 수정했습니다.

```kotlin
package com.commerce.common.model.orders

// 주문상태
// PENDING: 주문 생성
// PROCESSING: 주문 처리중
// SHIPPED: 배송중
// DELIVERED: 배송완료
// CANCEL: 주문 취소
// REFUND: 환불
// EXCHANGE: 교환
enum class OrderStatus {
    PENDING,
    PROCESSING,
    SHIPPED,
    DELIVERED,
    CANCEL,
    REFUND,
    EXCHANGE
}
```

2024-09-07 05:26 UTC, hyunolike commented
@psh10066 

주요 수정요청사항에 대해 수정 완료했습니다. 
확인부탁드립니다. 감사합니다.

추가 개발 에정 사항 공유
- 주문 전 조회 API
- 주문 API
- 주문 상세 API

2024-09-07 06:07 UTC, psh10066 approved these changes
기능 동작에는 문제가 없도록 구성 잘해주신 것 같습니다!
prettyPrint 부분만 먼저 올라간다음 일단 바로 머지되어도 괜찮을 것 같아요.
코드 디테일은 나중에 수정해봅시다

2024-09-07 06:07 UTC, psh10066 commented on commerce-service/commerce-order/src/test/kotlin/com/commerce/service/order/controller/OrdersControllerTest.kt
> +            .andDo(document("get-orders",
여기 아래에 아래 코드 추가해 주세요! (모든 API 테스트 공통)
html로 만들어진 결과 문서를 확인해 보시면 없을 때와 있을 때의 차이가 보이실 겁니당

```java
preprocessRequest(prettyPrint()),
preprocessResponse(prettyPrint()),
```

2024-09-07 06:07 UTC, psh10066 commented on commons/model/build.gradle.kts
> +    api("org.springframework.boot:spring-boot-starter-data-jpa") // Pageable 가져오기 위한 의존성 추가
api와 implementation의 차이가 있는데요,
api를 사용하게 되면 현재의 model 모듈을 의존받아서 사용하는 모든 곳에서 같은 의존성이 다운로드되도록 하고,
implementation은 현재의 model 모듈에서만 jpa 의존성이 생기게 됩니다.

persistence 모듈에서는 DB 성향이 강하니 일부러 이 모듈을 의존받으면 jpa 의존을 받도록 구현해둔 것이라서
model에서는 implementation으로 변경하는게 좋을 것 같습니다.

2024-09-07 06:07 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +            ordersRepository.findByCreatedAtBetweenAndStatus(startDate, endDate, status, pageable)
order에는 이미 orderDate라는 주문 날짜가 존재합니다.
createdAt은 DB에서 기록하는 필드에 가깝기 때문에 웬만하면 정렬이나 기간 조회 등 모두에서 orderDate를 사용했으면 좋겠어요.

2024-09-07 06:07 UTC, psh10066 commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +            ordersRepository.findByCreatedAtBetweenAndStatus(startDate, endDate, status, pageable)
또한 여기에서 if else를 하는 것보다는, orderRepository에 status까지 일단 넘기고, repository에서 status가 있는 경우와 없는 경우에 따라 jpa 메서드를 달리 호출하도록 하는 게 좋을 것 같습니다. (서비스는 조회를 하는 것이 주목적이고, 어떻게 DB와 통신하고 쿼리를 만드는지는 몰라도 되기 때문에)

sort같은 경우도 repository로 page, size, sortOption을 넘기고 pageable 자체를 repository에서 만들어서 사용하는 게 더 책임 분리가 잘 된 것 아닌가 싶기도 해요.

2024-09-07 06:12 UTC, hyunolike commented on commerce-service/commerce-order/src/test/kotlin/com/commerce/service/order/controller/OrdersControllerTest.kt
> +            .andDo(document("get-orders",
오오 넣으니까 깔끔하게 보여요 
감사합니다 ! 
<img width="892" alt="image" src="https://github.com/user-attachments/assets/b293c624-9269-454e-a35e-09a37c921e5f">

2024-09-07 06:18 UTC, hyunolike commented on commons/model/build.gradle.kts
> +    api("org.springframework.boot:spring-boot-starter-data-jpa") // Pageable 가져오기 위한 의존성 추가
```kotlin
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa") // Pageable 가져오기 위한 의존성 추가
}

``` 

이거까지 변경했습니다! 감사합니다

2024-09-07 06:19 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +            ordersRepository.findByCreatedAtBetweenAndStatus(startDate, endDate, status, pageable)
> order에는 이미 orderDate라는 주문 날짜가 존재합니다. createdAt은 DB에서 기록하는 필드에 가깝기 때문에 웬만하면 정렬이나 기간 조회 등 모두에서 orderDate를 사용했으면 좋겠어요.

앗! 이거는 머지하고 수정하겠습니다!

2024-09-07 06:20 UTC, hyunolike commented on commerce-service/commerce-order/src/main/kotlin/com/commerce/service/order/applicaton/service/OrderService.kt
> +            ordersRepository.findByCreatedAtBetweenAndStatus(startDate, endDate, status, pageable)
> 또한 여기에서 if else를 하는 것보다는, orderRepository에 status까지 일단 넘기고, repository에서 status가 있는 경우와 없는 경우에 따라 jpa 메서드를 달리 호출하도록 하는 게 좋을 것 같습니다. (서비스는 조회를 하는 것이 주목적이고, 어떻게 DB와 통신하고 쿼리를 만드는지는 몰라도 되기 때문에)
> 
> sort같은 경우도 repository로 page, size, sortOption을 넘기고 pageable 자체를 repository에서 만들어서 사용하는 게 더 책임 분리가 잘 된 것 아닌가 싶기도 해요.

네 좀더 세분화해서 코드 리펙토링 진행하겠습니다!

2024-09-07 06:53 UTC, hyunolike commented
@psh10066 
주문 조회 API Get method 변경 작업 완료했습니다. 

확인부탁드립니다!

2024-09-07 07:47 UTC, hyunolike commented
> @psh10066 주문 조회 API Get method 변경 작업 완료했습니다.
> 
> 확인부탁드립니다!

rest docs 필수값 여부 및 설명 추가 했습니다. 
확인 부탁드려요~

<img width="948" alt="image" src="https://github.com/user-attachments/assets/a81cf369-bf4b-49b0-a946-5d951901b818">

2024-09-07 07:53 UTC, merged