#3 서비스 - 상품 기능 개발
FC-InnerCircle/icd01-team05_06-commerce-be pull request #9
Opened 2024-09-02 14:55 UTC by hun-cloud

## 서비스 - 상품 기능 개발
---
- 09.02 기준. 카테고리 전체 조회 개발 완료
- 카테고리 별 상품 조회

2024-09-02 15:41 UTC, psh10066 requested changes
코틀린이 처음이신데 기존 코드 잘 활용하셔서 깔끔하게 잘 작성해주신 것 같습니다.
일단 돌려보기 전에 보이는 부분만 리뷰 드렸고, 활동 시간에 제대로 돌려보고 리뷰 사항 있으면 언급 드리겠습니다.
그 전까지 테스트 코드, API 명세 부분 작업 이어서 진행 부탁드려요!

2024-09-02 15:41 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseEntity.kt
> +abstract class BaseEntity : BaseTimeEntity() {
EnableJpaAuditing 어노테이션으로 설정한 곳이 현재는 없어서, 아직은 자동 Auditing이 동작하지 않을 것으로 보이네요. 하지만 이 부분은 천천히 해도 되고 공통적인 부분일 거라서 추후에 맞춰가도 될 것 같습니다.

그리고 auditing으로 createdBy나 LastModifiedBy의 경우 설정을 좀 해줘야 하는 것으로 알아서 저는 실제로 적용해보지는 않았는데, 이참에 한번 시도해 봐도 괜찮을 것 같습니다~

2024-09-02 15:41 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseEntity.kt
> +    var lastModifiedBy: String? = null
잘 몰라서 물어보는 건데, 이 필드들은 var로 선언을 해주지 않으면 안되는 걸까요?
그리고 이미 저희가 최종 수정시각 필드명을 updatedAt 으로 선언했으니 이 필드도 updatedBy로 통일하는 게 좋을 것 같습니다~

2024-09-02 17:26 UTC, YunNote commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/application/service/ProductService.kt
> +        return ProductCategoryInfoDto.of(categories)
즉정한 하나의 값을 기반으로 새로운 객체를 생성하게 된다면 of도 좋지만 from으로 네이밍 변경해보시는건 어떨까요?
정적 펙토리 메서드에서 입력된 값을 조합하거나 로직을 통한생성시 주로 of 를 사용하는것으로 보여집니다!
어떻게 생각하시는지 의견 부탁드리겠습니다 :)

2024-09-02 17:26 UTC, YunNote commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/ProductController.kt
> +    fun getProductCategories(): ProductCategoryInfoDto {
보통 카테고리 도메인과 상품 도메인이 있다면 카테고리가 먼저 존재한 이후 상품 도메인이 존재할것으로 보여집니다.
그렇다면 Category도 하나의 독립된 생명주기를 갖는다면 "카테고리"와 "상품"이 독립된 생명주기를 갖는다는 가정하에 ID기반참조로 구성하는것도 하나의 방식이 될 수 있을듯 한데 어떻게 생각하시나요 ?

2024-09-02 17:26 UTC, YunNote commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/request/ProductQueryRequest.kt
> +    val size: Int = 20,
page와 size에 대해서 해당 API뿐만 아니라 다른부분에서도 사용할 수있기 때문에
 BasePageRequest와 같이 구현한 후 사용하는 Request에서 상속받는건 어떻게 생각하시나요?

2024-09-04 02:26 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseEntity.kt
> +    var lastModifiedBy: String? = null
https://chatgpt.com/share/efdfa191-6f03-4ef1-a505-d0203970a0f9

이러한 내용이 있는데 혹시 val로 적용해보신 경험이 있으실까요?

2024-09-04 02:29 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseEntity.kt
> +    var lastModifiedBy: String? = null
그리고 이미 저희가 최종 수정시각 필드명을 updatedAt 으로 선언했으니 이 필드도 updatedBy로 통일하는 게 좋을 것 같습니다~
-> updatedAt으로 통일 맞으실까요~?

2024-09-04 02:30 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/application/service/ProductService.kt
> +        return ProductCategoryInfoDto.of(categories)
of 와 from의 차이를 생각해본 적이 없는데
알아보니 from이 더 맞는 표현인 것 같습니다 감사합니다 :)

2024-09-04 02:38 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/request/ProductQueryRequest.kt
> +    val size: Int = 20,
동의합니다 감사합니다 👍

2024-09-04 02:38 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseEntity.kt
> +abstract class BaseEntity : BaseTimeEntity() {
감사합니다 👍

2024-09-04 02:43 UTC, hun-cloud commented on commerce-service/commerce-product/src/main/kotlin/com/commerce/service/product/controller/ProductController.kt
> +    fun getProductCategories(): ProductCategoryInfoDto {
제가 이해한 바로는 엔티티 설계에 대한 부분인 것 같은데 맞는지 확인 부탁드립니다.

독립된 엔티티로 가져가는 것을 의미하는 것으로 이해했습니다.
예를 들어 
```java
@Entity
data class Category(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false, unique = true)
    val name: String
)
```
```java
@Entity
data class Product(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false)
    val name: String,

    @Column(nullable = false)
    val price: BigDecimal,

    @Column(nullable = true)
    val description: String? = null,

    @Column(nullable = false)
    val categoryId: Long // id 기반 참조 구성?
)
```
이런 의미인지 확인 한번 부탁드립니다. 감사합니다 👍

2024-09-04 03:26 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseEntity.kt
> +    var lastModifiedBy: String? = null
일단 여기는 등록/수정 시각이 아닌, 등록/수정 주체를 남기는 필드들입니다!
따라서 updatedAt이 아닌 updatedBy가 맞을 것 같아요.

그리고 val로는 저도 적용해본 적이 없기는 한데, 저도 찾아보니 var로 해야 한다는 것 같네요! 그냥 놔둬도 괜찮을 것 같습니다.

2024-09-04 03:27 UTC, psh10066 commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseTimeEntity.kt
> +    val updatedAt: LocalDateTime? = null
여기 2개의 필드도 var로 선언해야 한다고 하는 것 같습니다.

2024-09-05 09:38 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseTimeEntity.kt
> +    val updatedAt: LocalDateTime? = null
넵 감사합니다!

2024-09-05 09:38 UTC, hun-cloud commented on commons/persistence-database/src/main/kotlin/com/commerce/common/persistence/BaseEntity.kt
> +    var lastModifiedBy: String? = null
넵 감사합니다!

2024-09-09 11:31 UTC, psh10066 approved these changes
리뷰 드린 부분들이 있긴 한데, 일단은 배포나 기능에 문제될 부분은 아니라서 승인 처리했습니다.
배포하고 나서 빠르게 맞춰봐도 좋을 것 같아요!

2024-09-09 11:31 UTC, psh10066 commented on commerce-service/commerce-product/src/test/kotlin/com/mock/FakeCategoryRepository.kt
> +        initData()
테스트 데이터의 경우 mock 객체보다는, service 테스트라면 service 자체적으로 생성해주시는게 좋습니다.
테스트는 직관성과 멱등성이 생명이기 때문에, 테스트 실행 시에 각 테스트마다 테스트 데이터가 격리되어 삽입되도록 하는 게 좋아요.
그래서 AuthServiceTest에서는 FakeMemberRepository()를 setUp에서 일부러 재생성하여 테스트 데이터를 격리합니다. (이렇게 되면 다른 테스트가 실행된다고 갑자기 지금 테스트가 깨지거나 할 일이 없습니다.)
ServiceTest에서 공통적으로 사용할 데이터라면 setUp에서 FakeMemberRepository() 생성 이후에 data.add()해주는 것도 좋은 방식이에요.

현재 구조는 또한 initData가 findAll() 내에 있게 되면 findAll()이 만약 2번 호출되면 data가 두번씩 들어가서 문제가 발생할 수 있어 보입니다.

2024-09-09 11:31 UTC, psh10066 commented on commerce-service/commerce-product/src/test/kotlin/com/mock/FakeProductRepository.kt
> +        initData()
여기도 위에 말씀드린 것처럼 테스트 데이터 격리가 필요해 보입니다!

2024-09-09 12:47 UTC, merged